CC=g++
CFLAGS=-g -c
LFLAGS= -g  -Wl,--unresolved-symbols=ignore-in-shared-libs

RUNTIME_PATH=$(DRIVERS)/hsa/runtime/
COMPILER_PATH=$(DRIVERS)/hsa/compiler
ASSEMBLER_PATH=$(COMPILER_PATH)/hsail-tools/libHSAIL

BUILD_DIR=build/lnx64a/B_dbg/
OBJS =  assemble.o elf_utils.o obsedian_vector_copy.o

INCS = -I $(RUNTIME_PATH)/inc
INCS += -I $(COMPILER_PATH)/finalizer/Interface
INCS += -I $(ASSEMBLER_PATH)
INCS += -I $(ASSEMBLER_PATH)/$(BUILD_DIR)


all: vector_copy

vector_copy: $(OBJS)
	$(CC) $(LFLAGS) $(OBJS) $(ASSEMBLER_PATH)/$(BUILD_DIR)/LIBHSAIL.a -lelf -L$(RUNTIME_PATH)/core/build/lnx64a/so/B_dbg/ -lhsa-runtime64 -o vector_copy

assemble.o: assemble.cpp
	$(CC) $(CFLAGS) $(INCS) assemble.cpp -std=c++0x

elf_utils.o: elf_utils.cpp
	$(CC) $(CFLAGS) $(INCS) elf_utils.cpp -std=c++0x

obsedian_vector_copy.o: obsedian_vector_copy.cpp
	$(CC) $(CFLAGS) $(INCS) obsedian_vector_copy.cpp -std=c++0x

clean:
	rm -rf *o vector_copy

